-- 식품분류별(CATEGORY) 가격이 제일 비싼 식품의 분류, 가격, 이름 조회
-- 식품 분류 : 과자, 국, 김치, 식용유
-- 식품 가격을 기준으로 내림차순 정렬

WITH P AS (
    SELECT MAX(PRICE) AS MAX_PRICE, CATEGORY FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)

SELECT FP.CATEGORY, MAX(PRICE), PRODUCT_NAME FROM FOOD_PRODUCT AS FP
INNER JOIN P ON FP.CATEGORY = P.CATEGORY
WHERE 1=1
AND FP.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY FP.CATEGORY
ORDER BY FP.PRICE DESC

# SELECT CATEGORY, PRICE, PRODUCT_NAME FROM FOOD_PRODUCT
# ORDER BY CATEGORY
