
-- 우유와 요거트를 둘다 구매한 cart_id

-- 효율성 고려 X
SELECT DISTINCT C1.CART_ID FROM CART_PRODUCTS AS C1
INNER JOIN CART_PRODUCTS AS C2 ON C1.CART_ID = C2.CART_ID
WHERE 1=1
AND C1.NAME LIKE 'Yogurt'
AND C2.NAME LIKE 'Milk'


-- 동일 품목 제외(동일한 카트 내에 우유 또는 요거트를 2개 담은 경우)
SELECT CART_ID FROM CART_PRODUCTS 
WHERE 1=1
AND NAME IN ('Yogurt', 'Milk')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) >= 2
