-- ANIMAL_INS : 보호소 정보
-- ANIMAL_OUTS : 입양 정보

SELECT INS.NAME, INS.DATETIME FROM ANIMAL_INS AS INS
LEFT OUTER JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE 1=1
AND OUTS.NAME IS NULL
AND INS.NAME IS NOT NULL
ORDER BY DATETIME
LIMIT 3
