
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME from ANIMAL_INS
    INNER JOIN ANIMAL_OUTS 
        ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE 1=1
    AND ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME -- 날짜비교에 주의
ORDER BY ANIMAL_INS.DATETIME
