/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-02-09 01:25:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원 관리 시스템 회원 가입 페이지</title>\r\n");
      out.write("<style >\r\n");
      out.write("\ttable{\r\n");
      out.write("\t\tmargin : auto;\r\n");
      out.write("\t\twidth : 800px;\r\n");
      out.write("\t\tborder : 1px solid gray;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t.td_title{\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\tfont-size: x-large;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("var chkId = false;\r\n");
      out.write("var idcheck;\r\n");
      out.write("\tfunction formCheck(f){\r\n");
      out.write("\t\tif(f.id.value.trim()==\"\"){\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\tf.id.value=\"\";\r\n");
      out.write("\t\t\tf.id.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("/* \t\tif(!chkId || idcheck!=f.id.value.trim()){\r\n");
      out.write("\t\t\talert(\"아이디 중복을 확인해주세요\");\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\tif(f.pass.value.trim()==\"\"){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\tf.pass.value=\"\";\r\n");
      out.write("\t\t\tf.pass.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.pass.value.length<5 || f.pass.value.length>10){\r\n");
      out.write("\t\t\talert(\"비밀번호는 5~10자로 설정하세요.\")\r\n");
      out.write("\t\t\tf.pass.value=\"\";\r\n");
      out.write("\t\t\tf.pass.check=\"\";\r\n");
      out.write("\t\t\tf.pass.focus();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.pass.value.trim()!=f.passcheck.value.trim()){\r\n");
      out.write("\t\t\talert(\"비밀번호가 동일하지 않습니다.\");\r\n");
      out.write("\t\t\tf.passcheck.value=\"\";\r\n");
      out.write("\t\t\tf.passcheck.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(isNaN)\r\n");
      out.write("\t\tif(f.name.value.trim()==\"\"){\r\n");
      out.write("\t\t\talert(\"이름을 입력하세요\");\r\n");
      out.write("\t\t\tf.name.value=\"\";\r\n");
      out.write("\t\t\tf.name.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.age.value.trim()==\"\"){\r\n");
      out.write("\t\t\talert(\"나이를 입력하세요\");\r\n");
      out.write("\t\t\tf.age.value=\"\";\r\n");
      out.write("\t\t\tf.age.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.email.value.trim()==\"\"){\r\n");
      out.write("\t\t\talert(\"이메일 주소를 입력하세요\");\r\n");
      out.write("\t\t\tf.email.value=\"\";\r\n");
      out.write("\t\t\tf.email.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"joinform\" action=\"joinProcess.jsp\" method=\"post\">\r\n");
      out.write("\t<table border=1>\r\n");
      out.write("\t\t<tr><td colspan=\"2\" class=\"td_title\">회원 가입 페이지</td></tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><label for=\"id\">아이디 : </label></td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"id\" id=\"id\" required/> <input type=\"button\" \r\n");
      out.write("\t\t\tvalue=\"아이디 중복확인\" id=\"idCheck\" onclick=\"window.open('idCheck1.jsp?openInit=true', '', 'width=300, height=200')\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><label for=\"pass\">비밀번호 : </label></td>\r\n");
      out.write("\t\t\t<td><input type=\"password\" name=\"pass\" id=\"pass\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><label for=\"passcheck\">비밀번호 확인 : </label></td>\r\n");
      out.write("\t\t\t<td><input type=\"password\" name=\"passcheck\" id=\"passcheck\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><label for=\"name\">이름 : </label></td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"name\" id=\"name\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><label for=\"age\">나이 : </label></td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"age\" id=\"age\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><label for=\"gender1\"></label>성별 : </td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"남\" checked id=\"gender1\"/>남자\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"여\" id=\"gender2\"/>여자\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><label for=\"email\">이메일 주소 : </label></td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"email\" id=\"email\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><label for=\"zip\">우편번호 : </label></td>\r\n");
      out.write("\t\t\t<td align=left><input type=\"text\" name=\"zip\" id=\"zip\" size=\"6\" readonly/> <input type=\"button\" name=\"zipSearch\" id=\"zipSearch\" \r\n");
      out.write("\t\t\tvalue=\"검색\" onclick=\"window.open('zip.jsp', '', 'width=500, height=500')\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><label for=\"addr1\" >주소 : </label></td>\r\n");
      out.write("\t\t\t<td align=left><input type=\"text\" name=\"addr1\" id=\"addr1\" size=50 readonly/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><label for=\"addr2\" >주소 상세 : </label></td>\r\n");
      out.write("\t\t\t<td align=left><input type=\"text\" name=\"addr2\" id=\"addr2\" size=50 readonly/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<!-- <form onsubmit = \"return 함수()\" -->\r\n");
      out.write("\t\t\t\t<a href=\"javascript:formCheck(document.joinform)\">회원 가입</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"javascript:joinform.reset()\">다시작성</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
