# -- 회원 정보 : USER_INFO,  온라인 상품 판매 정보 : ONLINE_SALE
# -- 회원 ID : USER_ID
# # -- 날짜 : SALES_DATE, 년을 기준으로 오름차순 정렬, 년이 같다면 월을 기준으로 오름차순 정렬

# SELECT * FROM USER_INFO AS USER
# # INNER JOIN ONLINE_SALE AS SALE ON USER.USER_ID = SALE.USER_ID
# WHERE 1=1
# AND USER.JOINED LIKE '%2021%'
# ORDER BY SALES_DATE


SELECT LEFT(SALES_DATE, 4) AS YEAR,
    SUBSTRING(SALES_DATE, 6, 2) AS MONTH, 
    COUNT(DISTINCT USER.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT USER.USER_ID)/(
SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO
    WHERE JOINED LIKE '%2021%'
), 1) AS PUCHASED_RATIO -- 월별 구매 유저 / 2021년 전체 유저, 소수점 첫재 자리 까지만
    FROM USER_INFO AS USER
INNER JOIN ONLINE_SALE AS SALE ON USER.USER_ID = SALE.USER_ID
WHERE USER.JOINED LIKE '%2021%' -- 2021년도 유저만
GROUP BY SUBSTRING(SALES_DATE, 6, 2) -- 월별로 그룹 구분
ORDER BY SALES_DATE
